<a href="https://colab.research.google.com/github/JINO99/DAP_/blob/main/lecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

np.random.seed(0)

# NumPy Exercises!
Complete the solution code to have a desired output.

**[Caution!]** Not allow to use iteration, such as for-loop.





### 1-1. Create a 5×5 numpy array of all False boolean’s 
[ref] [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html)

In [ ]:
# Input
arr_size = (5, 5)

# Solution
bool_arr = np.full(arr_size ,False,dtype=bool)

# Print
print(bool_arr)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


### 1-2. Create a 7×7 diagonal matrix with diagonal index as 3.
diagonal matrix: 2-D array with ones on the diagonal and zeros elsewhere. 
(hint, ref [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))

In [ ]:
# Input
size = 7

# Solution
np_arr = np.eye(size,k=3)

# Print
print(np_arr)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 2. Extract even odd numbers from given `arr`

In [ ]:
# Input
arr = np.arange(35)

# Solution
arr = arr[arr%2==0]

# Print
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


### 3. Get the positions where elements of `a` and `b` match
(hint, refer [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html).)



In [ ]:
# Input
a = np.array([1, 7, 3, 2, 3, 5, 3, 4, 5, 8, 2, 6, 9])
b = np.array([1, 2, 10, 8, 3, 4, 9, 4, 9, 8, 5, 3, 5])

# Solution
idx = np.where(a==b)

# Print
print(idx)

(array([0, 4, 7, 9]),)


### 4. Find the median, standard deviation, average of iris's `sepallength` (1st column).

In [ ]:
from numpy.lib.function_base import median
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
med, std, avg = np.median(sepallength), np.std(sepallength),np.average(sepallength)

# Print
print(med, std, avg)

5.8 0.8253012917851409 5.843333333333334


### 5. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
(hint, refer [np.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).)

In [ ]:
# Input
np.random.seed(50)
a = np.random.randint(0, 10, 10)
print('Array: ', a)

# Solution
## Create an all True array
out = np.full(a.shape[0], True)

## Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]

## Mark those positions as False
out[unique_positions] = False

print('Duplicate entrie: ', out)

Array:  [0 0 1 4 6 5 6 6 5 2]
Duplicate entrie:  [False  True False False False False  True  True  True False]


# Pandas Exercises!
Complete the solution code to have a desired output. 





### 6. Combine `ser1` and `ser2` to form a dataframe.

In [ ]:
# Input
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 
df = pd.DataFrame({'A': ser1, 'B' : ser2})

# Print
print(df.tail())

    A   B
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25


### 7. Check if `df` has any missing values.

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head())

# Solution
print('\nIs there any missing value?:', df.isnull().values.any())

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

### 8. Create a TimeSeries starting `2022-09-01` and 7 weekends (mondays) after that **having** random numbers as values?

In [ ]:
# Solution
ser = pd.Series(pd.date_range("2022-09-01", periods=7,freq="W-MON"))
print(ser)

0   2022-09-05
1   2022-09-12
2   2022-09-19
3   2022-09-26
4   2022-10-03
5   2022-10-10
6   2022-10-17
dtype: datetime64[ns]


### 9. In `df`, compute the median price of every fruit using grouping function.

In [ ]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange', 'blueberry', 'melon'] * 5,
                   'rating': np.random.rand(25),
                   'price': np.random.randint(0, 20, 25)})

# Solution
df.groupby('fruit')['price'].median()

fruit
apple         9.0
banana       11.0
blueberry    11.0
melon         4.0
orange        6.0
Name: price, dtype: float64

### 10. Join two dataframes `df1` and `df2` for intersection items on `use_id`.
For `df2`, please select only `use_id`, `platform`, `device` columns not all columns for merging.

In [ ]:
# Input
base_path = 'https://raw.githubusercontent.com/shanealynn/Pandas-Merge-Tutorial/master/'
df1 = pd.read_csv(base_path + 'user_usage.csv')
df2 = pd.read_csv(base_path + 'user_device.csv')

# Solution
pd.merge(df1, df2[['use_id', 'platform', 'device']], on='use_id').head

<bound method NDFrame.head of      outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
0                      21.97                    4.82     1557.33   22787   
1                    1710.08                  136.88     7267.55   22788   
2                    1710.08                  136.88     7267.55   22789   
3                      94.46                   35.17      519.12   22790   
4                      71.59                   79.26     1557.33   22792   
..                       ...                     ...         ...     ...   
154                   198.59                   90.49     5191.12   23043   
155                   198.59                   90.49     3114.67   23044   
156                   106.65                   82.13     5191.12   23046   
157                   344.53                   20.53      519.12   23049   
158                    42.75                   46.83     5191.12   23053   

    platform                  device  
0    android      

## TODO! Analyze [Titanic](https://www.kaggle.com/c/titanic) Data
#### (until 21th Sep 2022)



### 0. Data load

In [1]:
import seaborn as sns

# Input
df = sns.load_dataset("titanic")

### 1. Show the first five samples of DataFrame 

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### 2. Print a concise summary of a DataFrame.
Column names, missing values for each column, and data type for each column.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

### 3. Generate descriptive statistics.

In [ ]:
df.describe()

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

### 4. Check the number of missing samples per each column

In [ ]:
df.isnull().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

### 5. Return a Series containing counts of unique values on `class` column.

In [3]:
df['class'].value_counts().sort_index()

First     216
Second    184
Third     491
Name: class, dtype: int64

### 6. Calculate the mean of `fare` according to `class` and `sex`
(hint, us `df.groupby`)

In [4]:
df.groupby(['class', 'sex'])['fare'].mean()

class   sex   
First   female    106.125798
        male       67.226127
Second  female     21.970121
        male       19.741782
Third   female     16.118810
        male       12.661633
Name: fare, dtype: float64

### 7. Do same thing by using `df.pivot_table`

In [8]:
df.pivot_table(values='fare',index=["class","sex"], aggfunc=np.mean)

fare
class  sex               
First  female  106.125798
       male     67.226127
Second female   21.970121
       male     19.741782
Third  female   16.118810
       male     12.661633